# Configuration file for video composition and comparison

# List of video entries. Each entry must have a 'path' and 'description'.
# All videos must have the same resolution, frame rate, and duration.
# The number of videos must be between 1 and 4 (inclusive).
videos:
  - path: model_centerpoint.mp4
    description: "centerpoint, confidence 0.35 for all classes"
  - path: model_bevfusion.mp4
    description: "bevfusion, confidence 0.35 for all classes"

# The path where the composite output video will be saved.
output_video: ./output_videos/centerpoint_vs_bevfusion.mp4

# --- Text Area Settings ---
# Height in pixels for the description area below each video frame.
text_area_height: 80

# Background color for the text area. Can be a color name (e.g., "white", "black", "red")
# or an RGB tuple (e.g., [255, 0, 0] for red).
text_area_color: [240, 240, 240] # Light grey

# Font size for the description text.
font_size: 25

# Color for the description text. Can be a color name or an RGB tuple.
font_color: "black"

# Note: Ensure the 'description' text is concise enough to fit within the
# text_area_height and video width. 'moviepy' will attempt basic wrapping
# with method='caption', but long text may still be cut off.
